#----------------------------------------------------------------------
# CS415/515 Assignment 3
#----------------------------------------------------------------------

FLAGS = -std=c99 -g -lm
CC = mpicc

DEFAULT:
	g++ -o verify verify.c -std=c99
        g++ -o datagen datagen.c
        g++ -o simpleqsort simpleqsort.c
        mpicc -o exsort exsort.c -std=c99
 
